//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Orders: [
      {
        orderNumber: 1,
        customerName: 'customerName 1',
        orderDate: '2023-08-15T01:07:26.582Z',
        items: 'items 1',
        totalAmount: 0.59,
        shippingAddress: 'shippingAddress 1',
        orderStatus: 'orderStatus 1',
        id: 20,
      },
      {
        orderNumber: 2,
        customerName: 'customerName 2',
        orderDate: '2025-03-19T20:53:58.832Z',
        items: 'items 2',
        totalAmount: 0.1,
        shippingAddress: 'shippingAddress 2',
        orderStatus: 'orderStatus 2',
        id: 23,
      },
      {
        orderNumber: 3,
        customerName: 'customerName 3',
        orderDate: '2023-06-24T10:04:57.191Z',
        items: 'items 3',
        totalAmount: 0.23,
        shippingAddress: 'shippingAddress 3',
        orderStatus: 'orderStatus 3',
        id: 62,
      },
      {
        orderNumber: 4,
        customerName: 'customerName 4',
        orderDate: '2024-03-20T21:47:35.339Z',
        items: 'items 4',
        totalAmount: 0.32,
        shippingAddress: 'shippingAddress 4',
        orderStatus: 'orderStatus 4',
        id: 53,
      },
      {
        orderNumber: 5,
        customerName: 'customerName 5',
        orderDate: '2024-10-09T00:14:16.286Z',
        items: 'items 5',
        totalAmount: 0.18,
        shippingAddress: 'shippingAddress 5',
        orderStatus: 'orderStatus 5',
        id: 71,
      },
    ],
  },
};
export default data;
