//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Orders: {
      name: 'Orders',
      fields: {
        orderNumber: 'Order Number',
        customerName: 'Customer Name',
        orderDate: 'Order Date',
        items: 'Items',
        totalAmount: 'Total Amount',
        shippingAddress: 'Shipping Address',
        orderStatus: 'Order Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Orders: {
      name: 'Orders (fr)',
      fields: {
        orderNumber: 'Order Number (fr)',
        customerName: 'Customer Name (fr)',
        orderDate: 'Order Date (fr)',
        items: 'Items (fr)',
        totalAmount: 'Total Amount (fr)',
        shippingAddress: 'Shipping Address (fr)',
        orderStatus: 'Order Status (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
